import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from "@/components/NarBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        <main className="container mx-auto h-screen flex flex-col gap-5 justify-center items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
